"""Add test_cases_json and entrypoint

Revision ID: d2a68bcfae02
Revises: 'f708a51d6e58'
Create Date: 2026-08-21 10:07:16.847763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a68bcfae02'
down_revision: Union[str, None] = 'f708a51d6e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('test_cases_json', sa.JSON(), nullable=False))
    op.add_column('exercises', sa.Column('entrypoint', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'entrypoint')
    op.drop_column('exercises', 'test_cases_json')
    # ### end Alembic commands ###
