"""Add learning domain models.

Revision ID: 301f506f70c6
Revises: None
Create Date: 2026-07-28 09:17:52.634851

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "301f506f70c6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Auth tables are intentionally kept; removed erroneous drop commands generated by alembic.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Auth tables are intentionally kept; removed erroneous create commands generated by alembic.
    # ### end Alembic commands ###
